spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: eventez
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: never

server:
  servlet:
    session:
      timeout: 24h
