spring:
  application:
    name: eventez

  profiles:
    active: dev

  jackson:
    default-property-inclusion: non_null

  config:
    import: "optional:file:.env[.properties]"

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB
      enabled: true

server:
  servlet:
    context-path: /api

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  folder: ${CLOUDINARY_FOLDER}

jwt:
  secret: ${JWT_SECRET}
  expiry: ${JWT_EXPIRY}
