CREATE TYPE user_role AS ENUM ('PLANNER', 'PROVIDER');
CREATE TYPE price_type AS ENUM ('FIXED', 'HOURLY', 'PER_EVENT', 'CUSTOM');
CREATE TYPE media_type AS ENUM ('IMAGE', 'VIDEO');
CREATE TYPE availability_status AS ENUM ('AVAILABLE', 'BOOKED', 'TENTATIVE', 'BLOCKED');
CREATE TYPE event_type AS ENUM ('WEDDING', 'CORPORATE', 'BIRTHDAY', 'CONFERENCE', 'PARTY', 'SOCIAL', 'FUNDRAISER', 'OTHER');
CREATE TYPE event_status AS ENUM ('DRAFT', 'ACTIVE', 'COMPLETED', 'CANCELLED');
CREATE TYPE inquiry_status AS ENUM ('PENDING', 'READ', 'RESPONDED', 'CLOSED');
